// Generated by script/generate_aircraft_icons.py - do not edit by hand; change the script and run it again.
//
// Aircraft map icon geometry in a unit square (x right, y down, nose at y = -1). Each part is a painted layer;
// `AircraftIconRenderer` (the app) knows how to paint each `Paint`. A preview sheet is in docs/aircraft-icons.png.

enum AircraftIconData {
    /// Icon parts by `AircraftIconKind` raw value.
    static let parts: [String: [AircraftIconPart]] = [
        "light": lightParts,
        "small": smallParts,
        "bizjet": bizjetParts,
        "large": largeParts,
        "highVortexLarge": highVortexLargeParts,
        "heavy": heavyParts,
        "highPerformance": highPerformanceParts,
        "rotorcraft": rotorcraftParts,
        "glider": gliderParts,
        "lighterThanAir": lighterThanAirParts,
        "parachutist": parachutistParts,
        "ultralight": ultralightParts,
        "uav": uavParts,
        "spaceVehicle": spaceVehicleParts,
        "surfaceEmergency": surfaceEmergencyParts,
        "surfaceService": surfaceServiceParts,
        "pointObstacle": pointObstacleParts,
        "clusterObstacle": clusterObstacleParts,
        "lineObstacle": lineObstacleParts,
        "unknown": unknownParts,
    ]

    private static let lightParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.9, 0.05, -0.88, 0.075, -0.78, 0.078, -0.3, 0.06, 0.4, 0.03, 0.85, 0, 0.9, -0.03, 0.85, -0.06, 0.4, -0.078, -0.3, -0.075, -0.78, -0.05, -0.88]),
        .polygon(.body, [0.07, -0.34, 0.92, -0.3, 0.92, -0.08, 0.07, -0.06]),
        .polygon(.body, [-0.07, -0.06, -0.92, -0.08, -0.92, -0.3, -0.07, -0.34]),
        .polygon(.dark, [0.03, 0.66, 0.36, 0.68, 0.36, 0.84, 0.03, 0.84]),
        .polygon(.dark, [-0.03, 0.84, -0.36, 0.84, -0.36, 0.68, -0.03, 0.66]),
        .polygon(.glass, [-0.045, -0.58, 0.045, -0.58, 0.058, -0.36, -0.058, -0.36]),
        .polygon(.highlight, [-0.04, -0.8, -0.018, -0.8, -0.018, 0.5, -0.04, 0.5]),
        .ellipse(.disc, 0, -0.93, 0.34, 0.035),
        .line(.line, -0.34, -0.93, 0.34, -0.93, 0.03),
    ]

    private static let smallParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.95, 0.04, -0.93, 0.07, -0.82, 0.08, -0.55, 0.078, 0.4, 0.05, 0.75, 0, 0.92, -0.05, 0.75, -0.078, 0.4, -0.08, -0.55, -0.07, -0.82, -0.04, -0.93]),
        .polygon(.body, [0.07, -0.26, 0.9, -0.2, 0.9, 0.02, 0.07, 0.04]),
        .polygon(.body, [-0.07, 0.04, -0.9, 0.02, -0.9, -0.2, -0.07, -0.26]),
        .polygon(.dark, [0.03, 0.68, 0.34, 0.72, 0.34, 0.88, 0.03, 0.88]),
        .polygon(.dark, [-0.03, 0.88, -0.34, 0.88, -0.34, 0.72, -0.03, 0.68]),
        .polygon(.light, [0.3, -0.62, 0.36, -0.62, 0.37, 0.02, 0.29, 0.02]),
        .polygon(.light, [-0.29, 0.02, -0.37, 0.02, -0.36, -0.62, -0.3, -0.62]),
        .ellipse(.disc, 0.33, -0.66, 0.16, 0.025),
        .ellipse(.disc, -0.33, -0.66, 0.16, 0.025),
        .polygon(.glass, [-0.04, -0.72, 0.04, -0.72, 0.052, -0.52, -0.052, -0.52]),
        .polygon(.highlight, [-0.05, -0.85, -0.025, -0.85, -0.025, 0.4, -0.05, 0.4]),
    ]

    private static let bizjetParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.03, -0.96, 0.055, -0.86, 0.072, -0.7, 0.075, 0.3, 0.06, 0.62, 0.03, 0.88, 0, 0.94, -0.03, 0.88, -0.06, 0.62, -0.075, 0.3, -0.072, -0.7, -0.055, -0.86, -0.03, -0.96]),
        .polygon(.body, [0.07, -0.12, 0.8, 0.22, 0.8, 0.31, 0.07, 0.24]),
        .polygon(.body, [-0.07, 0.24, -0.8, 0.31, -0.8, 0.22, -0.07, -0.12]),
        .polygon(.dark, [0.04, 0.72, 0.34, 0.86, 0.34, 0.94, 0.04, 0.92]),
        .polygon(.dark, [-0.04, 0.92, -0.34, 0.94, -0.34, 0.86, -0.04, 0.72]),
        .polygon(.light, [0.085, 0.3, 0.135, 0.28, 0.165, 0.34, 0.165, 0.66, 0.085, 0.66]),
        .polygon(.light, [-0.085, 0.66, -0.165, 0.66, -0.165, 0.34, -0.135, 0.28, -0.085, 0.3]),
        .polygon(.glass, [-0.03, -0.82, 0.03, -0.82, 0.042, -0.72, -0.042, -0.72]),
        .polygon(.highlight, [-0.045, -0.7, -0.02, -0.7, -0.02, 0.35, -0.045, 0.35]),
    ]

    private static let largeParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.036, -0.97, 0.0648, -0.9, 0.0846, -0.78, 0.09, -0.62, 0.09, 0.5, 0.0702, 0.75, 0.0342, 0.93, 0, 0.98, -0.0342, 0.93, -0.0702, 0.75, -0.09, 0.5, -0.09, -0.62, -0.0846, -0.78, -0.0648, -0.9, -0.036, -0.97]),
        .polygon(.body, [0.081, -0.22, 0.96, 0.25, 0.96, 0.34, 0.3648, 0.24, 0.081, 0.24]),
        .polygon(.body, [-0.081, 0.24, -0.3648, 0.24, -0.96, 0.34, -0.96, 0.25, -0.081, -0.22]),
        .polygon(.dark, [0.054, 0.66, 0.42, 0.9, 0.42, 0.97, 0.054, 0.9]),
        .polygon(.dark, [-0.054, 0.9, -0.42, 0.97, -0.42, 0.9, -0.054, 0.66]),
        .polygon(.light, [0.285, -0.1822, 0.32, -0.2072, 0.355, -0.1822, 0.355, -0.0222, 0.285, -0.0222]),
        .polygon(.light, [-0.285, -0.0222, -0.355, -0.0222, -0.355, -0.1822, -0.32, -0.2072, -0.285, -0.1822]),
        .polygon(.glass, [-0.035, -0.86, 0.035, -0.86, 0.05, -0.79, -0.05, -0.79]),
        .polygon(.highlight, [-0.045, -0.72, -0.018, -0.72, -0.018, 0.5, -0.045, 0.5]),
    ]

    private static let highVortexLargeParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.0312, -0.97, 0.0562, -0.9, 0.0733, -0.78, 0.078, -0.62, 0.078, 0.5, 0.0608, 0.75, 0.0296, 0.93, 0, 0.98, -0.0296, 0.93, -0.0608, 0.75, -0.078, 0.5, -0.078, -0.62, -0.0733, -0.78, -0.0562, -0.9, -0.0312, -0.97]),
        .polygon(.body, [0.0702, -0.16, 0.86, 0.2, 0.86, 0.29, 0.3268, 0.24, 0.0702, 0.24]),
        .polygon(.body, [-0.0702, 0.24, -0.3268, 0.24, -0.86, 0.29, -0.86, 0.2, -0.0702, -0.16]),
        .polygon(.dark, [0.0468, 0.66, 0.38, 0.9, 0.38, 0.97, 0.0468, 0.9]),
        .polygon(.dark, [-0.0468, 0.9, -0.38, 0.97, -0.38, 0.9, -0.0468, 0.66]),
        .polygon(.light, [0.265, -0.1453, 0.3, -0.1703, 0.335, -0.1453, 0.335, 0.0147, 0.265, 0.0147]),
        .polygon(.light, [-0.265, 0.0147, -0.335, 0.0147, -0.335, -0.1453, -0.3, -0.1703, -0.265, -0.1453]),
        .polygon(.glass, [-0.035, -0.86, 0.035, -0.86, 0.05, -0.79, -0.05, -0.79]),
        .polygon(.highlight, [-0.039, -0.72, -0.0156, -0.72, -0.0156, 0.5, -0.039, 0.5]),
    ]

    private static let heavyParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.046, -0.97, 0.0828, -0.9, 0.1081, -0.78, 0.115, -0.62, 0.115, 0.5, 0.0897, 0.75, 0.0437, 0.93, 0, 0.98, -0.0437, 0.93, -0.0897, 0.75, -0.115, 0.5, -0.115, -0.62, -0.1081, -0.78, -0.0828, -0.9, -0.046, -0.97]),
        .polygon(.body, [0.1035, -0.26, 1, 0.3, 1, 0.39, 0.38, 0.24, 0.1035, 0.24]),
        .polygon(.body, [-0.1035, 0.24, -0.38, 0.24, -1, 0.39, -1, 0.3, -0.1035, -0.26]),
        .polygon(.dark, [0.069, 0.66, 0.46, 0.9, 0.46, 0.97, 0.069, 0.9]),
        .polygon(.dark, [-0.069, 0.9, -0.46, 0.97, -0.46, 0.9, -0.069, 0.66]),
        .polygon(.light, [0.235, -0.246, 0.27, -0.271, 0.305, -0.246, 0.305, -0.086, 0.235, -0.086]),
        .polygon(.light, [-0.235, -0.086, -0.305, -0.086, -0.305, -0.246, -0.27, -0.271, -0.235, -0.246]),
        .polygon(.light, [0.485, -0.0898, 0.52, -0.1148, 0.555, -0.0898, 0.555, 0.0702, 0.485, 0.0702]),
        .polygon(.light, [-0.485, 0.0702, -0.555, 0.0702, -0.555, -0.0898, -0.52, -0.1148, -0.485, -0.0898]),
        .polygon(.glass, [-0.035, -0.86, 0.035, -0.86, 0.05, -0.79, -0.05, -0.79]),
        .polygon(.highlight, [-0.0575, -0.72, -0.023, -0.72, -0.023, 0.5, -0.0575, 0.5]),
    ]

    private static let highPerformanceParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.03, -0.86, 0.06, -0.5, 0.075, 0.4, 0.06, 0.88, 0, 0.92, -0.06, 0.88, -0.075, 0.4, -0.06, -0.5, -0.03, -0.86]),
        .polygon(.body, [0.06, -0.3, 0.72, 0.56, 0.72, 0.68, 0.06, 0.62]),
        .polygon(.body, [-0.06, 0.62, -0.72, 0.68, -0.72, 0.56, -0.06, -0.3]),
        .polygon(.dark, [0.05, 0.66, 0.3, 0.86, 0.3, 0.94, 0.05, 0.9]),
        .polygon(.dark, [-0.05, 0.9, -0.3, 0.94, -0.3, 0.86, -0.05, 0.66]),
        .polygon(.glass, [-0.035, -0.58, 0.035, -0.58, 0.05, -0.24, -0.05, -0.24]),
        .polygon(.light, [-0.045, 0.78, -0.012, 0.78, -0.012, 0.94, -0.045, 0.94]),
        .polygon(.light, [0.012, 0.78, 0.045, 0.78, 0.045, 0.94, 0.012, 0.94]),
        .polygon(.highlight, [-0.05, -0.6, -0.028, -0.6, -0.028, 0.6, -0.05, 0.6]),
    ]

    private static let rotorcraftParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.58, 0.1, -0.52, 0.165, -0.32, 0.17, 0.02, 0.11, 0.24, 0.04, 0.36, 0, 0.38, -0.04, 0.36, -0.11, 0.24, -0.17, 0.02, -0.165, -0.32, -0.1, -0.52]),
        .polygon(.body, [-0.032, 0.22, 0.032, 0.22, 0.024, 0.86, -0.024, 0.86]),
        .polygon(.dark, [-0.1, 0.76, 0.1, 0.8, 0.1, 0.88, -0.1, 0.86]),
        .polygon(.glass, [-0.09, -0.5, 0.09, -0.5, 0.12, -0.3, -0.12, -0.3]),
        .polygon(.highlight, [-0.09, -0.24, -0.05, -0.24, -0.05, 0.16, -0.09, 0.16]),
        .ellipse(.disc, 0, -0.05, 0.86, 0.86),
        .line(.line, -0.8, 0.3, 0.8, -0.4, 0.045),
        .line(.line, -0.62, -0.6, 0.62, 0.5, 0.045),
        .ellipse(.disc, 0, 0.84, 0.07, 0.13),
    ]

    private static let gliderParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.86, 0.028, -0.8, 0.04, -0.6, 0.03, 0.62, 0.018, 0.9, 0, 0.93, -0.018, 0.9, -0.03, 0.62, -0.04, -0.6, -0.028, -0.8]),
        .polygon(.body, [0.03, -0.22, 1, -0.14, 1, -0.03, 0.03, 0.03]),
        .polygon(.body, [-0.03, 0.03, -1, -0.03, -1, -0.14, -0.03, -0.22]),
        .polygon(.dark, [0.02, 0.72, 0.26, 0.78, 0.26, 0.87, 0.02, 0.87]),
        .polygon(.dark, [-0.02, 0.87, -0.26, 0.87, -0.26, 0.78, -0.02, 0.72]),
        .polygon(.glass, [-0.03, -0.6, 0.03, -0.6, 0.04, -0.32, -0.04, -0.32]),
        .polygon(.highlight, [-0.03, -0.3, -0.012, -0.3, -0.012, 0.6, -0.03, 0.6]),
    ]

    private static let lighterThanAirParts: [AircraftIconPart] = [
        .ellipse(.body, 0, -0.12, 0.62, 0.7),
        .line(.line, -0.3, -0.7326, -0.3, 0.4926, 0.03),
        .line(.line, 0.3, -0.7326, 0.3, 0.4926, 0.03),
        .line(.line, 0, -0.82, 0, 0.58, 0.03),
        .ellipse(.highlight, -0.24, -0.4, 0.14, 0.24),
        .line(.line, -0.16, 0.56, -0.07, 0.72, 0.022),
        .line(.line, 0.16, 0.56, 0.07, 0.72, 0.022),
        .polygon(.dark, [-0.1, 0.7, 0.1, 0.7, 0.1, 0.88, -0.1, 0.88]),
    ]

    private static let parachutistParts: [AircraftIconPart] = [
        .ellipse(.body, 0, -0.18, 0.78, 0.46),
        .ellipse(.highlight, -0.3, -0.34, 0.24, 0.12),
        .line(.line, -0.72, -0.05, 0, 0.62, 0.02),
        .line(.line, 0.72, -0.05, 0, 0.62, 0.02),
        .line(.line, 0, 0.28, 0, 0.62, 0.02),
        .line(.line, -0.36, 0.1, 0, 0.62, 0.02),
        .line(.line, 0.36, 0.1, 0, 0.62, 0.02),
        .ellipse(.dark, 0, 0.68, 0.11, 0.11),
    ]

    private static let ultralightParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.9, 0.96, 0.4, 0.62, 0.5, 0, 0.16, -0.62, 0.5, -0.96, 0.4]),
        .line(.line, 0, -0.92, 0, 0.28, 0.03),
        .polygon(.highlight, [-0.04, -0.62, -0.01, -0.62, -0.34, 0.24, -0.4, 0.24]),
        .ellipse(.dark, 0, 0.08, 0.075, 0.22),
    ]

    private static let uavParts: [AircraftIconPart] = [
        .line(.line, -0.6, -0.6, 0.6, 0.6, 0.05),
        .line(.line, 0.6, -0.6, -0.6, 0.6, 0.05),
        .ellipse(.disc, -0.6, -0.6, 0.3, 0.3),
        .ellipse(.dark, -0.6, -0.6, 0.06, 0.06),
        .ellipse(.disc, 0.6, -0.6, 0.3, 0.3),
        .ellipse(.dark, 0.6, -0.6, 0.06, 0.06),
        .ellipse(.disc, -0.6, 0.6, 0.3, 0.3),
        .ellipse(.dark, -0.6, 0.6, 0.06, 0.06),
        .ellipse(.disc, 0.6, 0.6, 0.3, 0.3),
        .ellipse(.dark, 0.6, 0.6, 0.06, 0.06),
        .polygon(.body, [0, -0.26, 0.16, -0.2, 0.16, 0.2, 0.1, 0.26, 0, 0.26, -0.1, 0.26, -0.16, 0.2, -0.16, -0.2]),
        .polygon(.light, [0, -0.42, 0.08, -0.28, -0.08, -0.28]),
        .polygon(.glass, [-0.07, -0.1, 0.07, -0.1, 0.07, 0.06, -0.07, 0.06]),
    ]

    private static let spaceVehicleParts: [AircraftIconPart] = [
        .polygon(.body, [0, -1, 0.06, -0.86, 0.1, -0.5, 0.11, 0.7, 0.06, 0.95, 0, 0.95, -0.06, 0.95, -0.11, 0.7, -0.1, -0.5, -0.06, -0.86]),
        .polygon(.body, [0.1, -0.05, 0.84, 0.86, 0.84, 0.96, 0.1, 0.9]),
        .polygon(.body, [-0.1, 0.9, -0.84, 0.96, -0.84, 0.86, -0.1, -0.05]),
        .polygon(.dark, [-0.06, 0.8, -0.02, 0.8, -0.02, 0.98, -0.06, 0.98]),
        .polygon(.dark, [0.02, 0.8, 0.06, 0.8, 0.06, 0.98, 0.02, 0.98]),
        .polygon(.glass, [-0.04, -0.72, 0.04, -0.72, 0.06, -0.52, -0.06, -0.52]),
    ]

    private static let surfaceEmergencyParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.74, 0.24, -0.74, 0.31, -0.55, 0.32, 0.6, 0.27, 0.72, 0, 0.72, -0.27, 0.72, -0.32, 0.6, -0.31, -0.55, -0.24, -0.74]),
        .polygon(.glass, [0, -0.48, 0.22, -0.48, 0.25, -0.24, 0, -0.24, -0.25, -0.24, -0.22, -0.48]),
        .polygon(.light, [-0.24, -0.06, 0.24, -0.06, 0.24, 0.08, -0.24, 0.08]),
        .ellipse(.dark, -0.12, 0.01, 0.06, 0.06),
        .ellipse(.dark, 0.12, 0.01, 0.06, 0.06),
        .polygon(.highlight, [-0.28, 0.2, -0.2, 0.2, -0.2, 0.62, -0.28, 0.62]),
    ]

    private static let surfaceServiceParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.82, 0.24, -0.82, 0.27, -0.66, 0.27, -0.16, 0, -0.16, -0.27, -0.16, -0.27, -0.66, -0.24, -0.82]),
        .polygon(.dark, [0, -0.1, 0.31, -0.1, 0.31, 0.82, 0, 0.82, -0.31, 0.82, -0.31, -0.1]),
        .polygon(.glass, [0, -0.64, 0.2, -0.64, 0.22, -0.42, 0, -0.42, -0.22, -0.42, -0.2, -0.64]),
        .polygon(.highlight, [-0.27, 0, -0.2, 0, -0.2, 0.74, -0.27, 0.74]),
    ]

    private static let pointObstacleParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.68, 0.62, 0.52, -0.62, 0.52]),
        .line(.glass, 0, -0.22, 0, 0.14, 0.09),
        .ellipse(.glass, 0, 0.34, 0.06, 0.06),
    ]

    private static let clusterObstacleParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.76, 0.31, -0.16, -0.31, -0.16]),
        .ellipse(.glass, 0, -0.28, 0.045, 0.045),
        .polygon(.body, [-0.5, 0.02, -0.19, 0.62, -0.81, 0.62]),
        .ellipse(.glass, -0.5, 0.5, 0.045, 0.045),
        .polygon(.body, [0.5, 0.02, 0.81, 0.62, 0.19, 0.62]),
        .ellipse(.glass, 0.5, 0.5, 0.045, 0.045),
    ]

    private static let lineObstacleParts: [AircraftIconPart] = [
        .line(.line, -0.62, -0.02, 0.62, -0.02, 0.03),
        .polygon(.body, [-0.62, -0.2312, -0.4092, 0.1768, -0.8308, 0.1768]),
        .polygon(.body, [0.62, -0.2312, 0.8308, 0.1768, 0.4092, 0.1768]),
        .line(.line, -0.62, 0.2, 0.62, 0.2, 0.02),
    ]

    private static let unknownParts: [AircraftIconPart] = [
        .polygon(.body, [0, -0.9, 0.4, 0.66, 0, 0.34, -0.4, 0.66]),
        .ellipse(.dark, 0, 0.02, 0.09, 0.09),
        .polygon(.highlight, [-0.03, -0.62, -0.01, -0.62, -0.2, 0.42, -0.26, 0.42]),
    ]
}
